# 1.Create a null vector of size 10 but the fifth value is 1

In [2]:
import numpy as np
x=np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

# 2.Create a vector with values ranging from 10 to 49

In [3]:
import numpy as np
x=np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

# 3.Reverse a vector (first element becomes last)

In [4]:
import numpy as np
  
ini_array = np.array([1, 2, 3, 6, 4, 5])
  

print("initial array", str(ini_array))
  

# using flipud method to reverse
res = np.flipud(ini_array)
  
# printing result
print("final array", str(res))

initial array [1 2 3 6 4 5]
final array [5 4 6 3 2 1]


# 4. Create a 3x3 matrix with values ranging from 0 to 8

In [6]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# 5.Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
import numpy as np
arr = np.array([[1,2,0,0,4,0]])
  
print ("Input  array : \n", arr)
    
ind = np.nonzero(arr)
print ("Indices of non zero elements : ", ind)

Input  array : 
 [[1 2 0 0 4 0]]
Indices of non zero elements :  (array([0, 0, 0], dtype=int64), array([0, 1, 4], dtype=int64))


# 6. Create a 3x3x3 array with random values

In [10]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

array([[[0.21783763, 0.91143149, 0.34217825],
        [0.90367237, 0.16824831, 0.34185048],
        [0.47580161, 0.94843695, 0.72461034]],

       [[0.31877844, 0.47030745, 0.76772368],
        [0.88429017, 0.63256583, 0.87159364],
        [0.52840598, 0.01177119, 0.67612709]],

       [[0.82575748, 0.84364883, 0.74097539],
        [0.66411241, 0.43015826, 0.50554962],
        [0.16933974, 0.32713148, 0.0089796 ]]])

# 7. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
print("Minimum Value  ",x.min())

print("Maximum Value  ",x.max())


Original Array:
[[0.30715386 0.91040163 0.05066957 0.69005631 0.34684216 0.00527647
  0.09411772 0.36024531 0.93082947 0.23478827]
 [0.01362787 0.40083061 0.82823245 0.96933238 0.13403456 0.12531582
  0.74724446 0.8963529  0.57172466 0.10502627]
 [0.97383727 0.96302775 0.37854794 0.36750707 0.62264966 0.89350111
  0.28729227 0.69460355 0.61683554 0.50777395]
 [0.89024699 0.82077235 0.94327215 0.17499319 0.59980146 0.16850679
  0.37591899 0.55406732 0.68219607 0.5353817 ]
 [0.37387123 0.84625649 0.58429582 0.48176124 0.2003208  0.16790085
  0.98523252 0.97518059 0.99099995 0.20073084]
 [0.50785941 0.50961624 0.02887061 0.82678639 0.60957032 0.08838552
  0.2313492  0.51874014 0.03017943 0.26720573]
 [0.2758829  0.52442316 0.01292232 0.33368959 0.38397992 0.0078384
  0.5392988  0.89210187 0.85991806 0.1405991 ]
 [0.19455266 0.38186026 0.81697612 0.92648678 0.37384008 0.46767265
  0.44464023 0.16507725 0.848207   0.49652416]
 [0.93708211 0.97880226 0.26809885 0.04440785 0.085267   0.336003

# 8.Create a random vector of size 30 and find the mean value

In [28]:
import numpy as np
Z = np.random.random(30)
print(Z)
m = Z.mean()
print ("The mean :",m)

[0.97301247 0.02727823 0.03440014 0.23175721 0.73478369 0.52528009
 0.81592709 0.06565772 0.69685514 0.8727061  0.08919907 0.03780006
 0.67880297 0.21934601 0.48625515 0.89437721 0.51895324 0.76448203
 0.91511232 0.16454589 0.36983674 0.77671046 0.55707796 0.866374
 0.3891105  0.63053338 0.45162204 0.46704451 0.96296549 0.47607668]
The mean : 0.5231294529277943


# 9.Create a 2d array with 1 on the border and 0 inside

In [19]:
import numpy as np
Z = np.ones((10,10))
Z[1:-1,1:-1]=0
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

# 10. Normalize a 5x5 matrix

In [21]:
import numpy as np
Z = np.random.random((5,5))
print("Original Matrix")
print(Z)
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print("New Matrix")
print (Z)

Original Matrix
[[0.76765205 0.75252249 0.78723513 0.39238966 0.95748193]
 [0.52296544 0.67972115 0.28170484 0.37208325 0.90727258]
 [0.98059936 0.21941864 0.13711262 0.29106119 0.81162991]
 [0.4747389  0.94460569 0.94926289 0.70388089 0.10165024]
 [0.61398914 0.67085518 0.29574316 0.66728918 0.62777878]]
New Matrix
[[0.75772509 0.74051186 0.78000521 0.33078071 0.97369878]
 [0.47933969 0.65768416 0.20485213 0.30767766 0.91657448]
 [1.         0.13398772 0.04034634 0.21549705 0.80775969]
 [0.42447127 0.95904919 0.9643478  0.68517123 0.        ]
 [0.58289938 0.64759714 0.22082383 0.64354002 0.59858817]]


# 11. Multiply a 5x3 matrix by a 3x2 matrix

In [22]:
import numpy as np
Z= np.dot(np.ones((5,3)), np.ones((3,2)))
print (Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


# 12. Negate all the elements which are in between 3x8 in place

In [23]:
import numpy as np
Z = np.arange(11)
print("Original")
print(Z)
Z[(3 < Z) & (Z < 8)] *= -1
print("New")
print(Z)

Original
[ 0  1  2  3  4  5  6  7  8  9 10]
New
[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


# 13. Find eigenvalues and eigenvectors of a square matrix

In [25]:
import numpy as np
x = np.random.random((2,2))
print("Original: ",x)
  
# finding eigenvalues and eigenvectors
w, v = np.linalg.eig(x)
  
# printing eigen values
print("Printing the Eigen values of the given square array:\n",
      w)
  
# printing eigen vectors
print("Printing Right eigenvectors of the given square array:\n",
      v)

Original:  [[0.00775664 0.79740193]
 [0.02583809 0.01073692]]
Printing the Eigen values of the given square array:
 [-0.13429961  0.15279317]
Printing Right eigenvectors of the given square array:
 [[-0.98449949 -0.9838581 ]
 [ 0.17538747 -0.17895036]]


# 14. Find inverse

In [27]:
import numpy as np
x = np.random.random((2,2))
print("Original:")
print(x)
print("Inverse")
print(np.linalg.inv(x))

Original:
[[0.22233539 0.22273605]
 [0.00084206 0.27527107]]
Inverse
[[ 4.51153535 -3.65051643]
 [-0.01380086  3.64394973]]
